vsync = true
display_index = 0
display_mode = 0
stars = 300
volume = 20
pause_on_hit = 0

levels = [
"FFFFFFFFFF FFFFFFFFFF FFFFFFFFFF FFFFFFFFFF FFFFFFFFFF ",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"HHHHHHHHHH FFFFFFFFFF FFFFFFFFFF FFFFFFFFFF FFFFFFFFFF ",
"HHHHHHHHHHHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"HHHHHHHHHHHHHHHHHHHHHHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHFFFFFFFFFFFFFFFFFFFFFF",
"HFHFHFHFHFHFHFHFHFHFHFHFHFHFHFHFHFHFHFHFHFHFHFHFHFHFHFH",
"FFFFFFFFFFFFHHHHHHHHHFFHHHHHHHHHFFHHHHHHHHHFFFFFFFFFFFF",
"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
"HHHHHHHHHHHHHHHHHHHHHHHDHDHDHDHDHFFFFFFFFFFFFFFFFFFFFFF",
"HHHHHHHHHHHHHHHHHHHHHHDDDDDDDDDDDFFFFFFFFFFFFFFFFFFFFFF",
"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDDDDDDDDDDDFFFFFFFFFFF",
"HHHHHHHHHHHHHHHHHHHHHHHDHDHDHDHDHDFDFDFDFDFDFFFFFFFFFFF",
"HHHHHHHHHHHHHHHHHHHHHHHFHFHFHFHFHFHFHFHFHFHFDDDDDDDDDDD",
"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHDFFFFFFFFFDDDDDDDDDDDD",
"HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHFDFDFDFDFDFDDDDDDDDDDD",
"HHHHHHHHHHHHHHHHHHHHHHDHHHHHHHHHDDFFFFFFFFFDDDDDDDDDDDD",
"DHHHHHHHHHDDHHHHHHHHHDDHHHHHHHHHDDFFFFFFFFFDDFFFFFFFFFD",
"BHBHBHBHBHBHHHHHHHHHHHHHHHHHHHHHHFFFFFFFFFFFFFFFFFFFFFF",
"BBBBBBBBBBBHHHHHHHHHHHHFHFHFHFHFHFFFFFFFFFFFFFFFFFFFFFF",
"BBBBBBBBBBBHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHFFFFFFFFFFF",
"BBBBBBBBBBBHHHHHHHHHHHHHHHHHHHHHHHFHFHFHFHFHDFDFDFDFDFD",
"BBBBBBBBBBBHHHHHHHHHHHHHHHHHHHHHHFDFDFDFDFDFDFDFDFDFDFD",
"BBBBBBBBBBBHHHHHHHHHHHHHHHHHHHHHHFHFHFHFHFHFDDDDDDDDDDD",
"HHHHHHHHHHHHHHHBBBHHHHHHHHBBBHHHHFFFFBBBFFFFDDDDDDDDDDD",
"HHHBBBBBHHHHHHBBBBBHHHFFFBBBBBFFFFFFFFFFFFFFFFFDDDDDFFF",
"FDFDBBBDFDFDFDFBBBFDFDFDFDBBBDFDFDFDFDFDFDFDFDFDFDFDFDF",
"BBBBBBBBBBBHHHHHHHHHHHDHHHHHHHHHDDFFFFFFFFFDDDDDDDDDDDD",
"DBBBBBBBBBDDHHHHHHHHHDDHHHHHHHHHDDFFFFFFFFFDDFFFFFFFFFD",
"BBBBBBBBBBBHSHSHSHSHSHHHHHHHHHHHHFFFFFFFFFFFDDDDDDDDDDD",
"BBBBBBBBBBBSSSSSSSSSSSHHHHHHHHHHHFFFFFFFFFFFDDDDDDDDDDD",
"BBBBBBBBBBBSSSSSSSSSSSHSHSHSHSHSHHHHHHHHHHHHDDDDDDDDDDD",
"BBBBBBBBBBBHSHSHSHSHSHHSHSHSHSHSHFDFDFDFDFDFFFFFFFFFFFF",
"HBHBHBHBHBHHSHSHSHSHSHHDHDHDHDHDHFDFDFDFDFDFHFHFHFHFHFH",
"BBBBBBBBBBBBHBHBHBHBHBSSSSSSSSSSSDFDFDFDFDFDDDDDDDDDDDD",
"SBSBSBSBSBSDFDFDFDFDFDBSBSBSBSBSBFDFDFDFDFDFDDDDDDDDDDD",
"HSHSHSHSHSHHSHSHSHSHSHHSHSHSHSHSHFDFDFDFDFDFFDFDFDFDFDF",
"BSBSBSBSBSBHSHSHSHSHSHHSHSHSHSHSHFDFDFDFDFDFFDFDFDFDFDF",
"HSHSHSHSHSHHSHSHSHSHSHHDHDHDHDHDHFDFDFDFDFDFFDFDFDFDFDF",
"BSBSBSBSBSBHSHSHSHSHSHHDHDHDHDHDHDDFDFDFDFDDDDDDDDDDDDD",
]

score_table = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,]

